apiVersion: v1
kind: Service
metadata:
  name: enterprise-system-20260525-190212-p8cn53sgbj7o-service
spec:
  selector:
    app: enterprise-system-20260525-190212-p8cn53sgbj7o
  ports:
  - port: 80
    targetPort: 8000
  type: ClusterIP
